/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#060e20',
        'on-secondary': '#005a3c',
        'on-surface': '#dee5ff',
        'primary-fixed': '#9396ff',
        'surface-container-low': '#091328',
        'outline': '#6d758c',
        'error': '#ff6e84',
        'error-dim': '#d73357',
        'surface-container-highest': '#192540',
        'on-surface-variant': '#a3aac4',
        'surface-variant': '#192540',
        'tertiary-fixed': '#f8a010',
        'surface-tint': '#a3a6ff',
        'primary-container': '#9396ff',
        'on-primary-container': '#0a0081',
        'secondary-dim': '#58e7ab',
        'primary-dim': '#6063ee',
        'tertiary-container': '#f8a010',
        'outline-variant': '#40485d',
        'error-container': '#a70138',
        'surface-container': '#0f1930',
        'primary-fixed-dim': '#8387ff',
        'tertiary-dim': '#e79400',
        'surface-container-lowest': '#000000',
        'primary': '#a3a6ff',
        'secondary-container': '#006c49',
        'surface-container-high': '#141f38',
        'background': '#060e20',
        'on-primary': '#0f00a4',
        'tertiary': '#ffb148',
        'on-background': '#dee5ff',
        'surface-bright': '#1f2b49',
        'secondary': '#69f6b8',
        'surface': '#060e20',
        'inverse-on-surface': '#4d556b',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
